name: 'Mirror GNU Emacs'
permissions: {}
on:
  workflow_dispatch:
  schedule:
    - cron: '42 * * * *'
jobs:
  mirror:
    name: 'Mirror GNU Emacs'
    runs-on: ubuntu-latest
    steps:
      - name: 'Create repository'
        run: |
          git init --bare -b master emacs.git

      - name: 'Configure refspec'
        working-directory: emacs.git
        run: |
          git config set remote.r.url https://github.com/emacsmirror/emacs
          git config set remote.r.fetch +refs/heads/master:refs/heads/master
          git config set --append remote.r.fetch +refs/heads/emacs-*:refs/heads/emacs-*
          git config set --append remote.r.fetch +refs/heads/feature/igc3:refs/heads/feature/igc3
          git config set --append remote.r.fetch +refs/tags/emacs-1*:refs/tags/emacs-1*
          git config set --append remote.r.fetch +refs/tags/emacs-2*:refs/tags/emacs-2*
          git config set --append remote.r.fetch +refs/tags/emacs-3*:refs/tags/emacs-3*

      - name: 'Pull from mirror'
        working-directory: emacs.git
        # When we add new branch by editing the above refspec
        # list, then that ref does not exist on the mirror yet.
        #
        # This is documented at https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#jobsjob_idstepscontinue-on-error
        # but if I do this I get an error "Unexpected value 'continue-or-error'".
        # continue-or-error: true
        # so instead use "... || true".
        run: |
          git fetch --no-tags r || true

      - name: 'Pull from upstream'
        working-directory: emacs.git
        run: |
          git remote set-url r https://git.savannah.gnu.org/git/emacs.git
          git fetch --no-tags r

      - name: 'Push to mirror'
        working-directory: emacs.git
        run: |
          git push --mirror https://${{ secrets.SAVANNAH_MIRROR_TOKEN }}@github.com/emacsmirror/emacs
          echo "emacs_head=$(git show --no-patch --format=%H)" >> $GITHUB_ENV

      - name: 'Update log'
        run: |
          git clone --single-branch --branch log https://${{ secrets.SAVANNAH_MIRROR_TOKEN }}@github.com/emacsmirror/.savannah
          cd .savannah
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "Updated Emacs master to ${{ env.emacs_head }}"
          git push https://${{ secrets.SAVANNAH_MIRROR_TOKEN }}@github.com/emacsmirror/.savannah log:log
